# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/FPGA_Verilog_labs/ZYBO_Master.xdc

# IP: ip/mult_ABC/mult_ABC.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_ABC || ORIG_REF_NAME==mult_ABC} -quiet] -quiet

# IP: ip/c_add_AB/c_add_AB.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_add_AB || ORIG_REF_NAME==c_add_AB} -quiet] -quiet
