# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Mateusz/Desktop/studia/AiR/SR/FPGA_Verilog_labs/MP_lab4/MP_lab4_matrix_multiplication/MP_lab4_matrix_multiplication.srcs/sources_1/ip/c_addsub_0/c_addsub_0.xci
# IP: The module: 'c_addsub_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mateusz/Desktop/studia/AiR/SR/FPGA_Verilog_labs/MP_lab4/MP_lab4_matrix_multiplication/MP_lab4_matrix_multiplication.gen/sources_1/ip/c_addsub_0/c_addsub_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_addsub_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Mateusz/Desktop/studia/AiR/SR/FPGA_Verilog_labs/MP_lab4/MP_lab4_matrix_multiplication/MP_lab4_matrix_multiplication.srcs/sources_1/ip/c_addsub_0/c_addsub_0.xci
# IP: The module: 'c_addsub_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mateusz/Desktop/studia/AiR/SR/FPGA_Verilog_labs/MP_lab4/MP_lab4_matrix_multiplication/MP_lab4_matrix_multiplication.gen/sources_1/ip/c_addsub_0/c_addsub_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_addsub_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
