# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Mateusz/Desktop/studia/AiR/SR/FPGA_Verilog_labs/MP_lab4/MP_lab4_complex_arithmetic_module/MP4_lab4_complex_arithmetic_module.srcs/sources_1/ip/c_add_DE/c_add_DE.xci
# IP: The module: 'c_add_DE' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mateusz/Desktop/studia/AiR/SR/FPGA_Verilog_labs/MP_lab4/MP_lab4_complex_arithmetic_module/MP4_lab4_complex_arithmetic_module.gen/sources_1/ip/c_add_DE/c_add_DE_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_add_DE'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Mateusz/Desktop/studia/AiR/SR/FPGA_Verilog_labs/MP_lab4/MP_lab4_complex_arithmetic_module/MP4_lab4_complex_arithmetic_module.srcs/sources_1/ip/c_add_DE/c_add_DE.xci
# IP: The module: 'c_add_DE' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mateusz/Desktop/studia/AiR/SR/FPGA_Verilog_labs/MP_lab4/MP_lab4_complex_arithmetic_module/MP4_lab4_complex_arithmetic_module.gen/sources_1/ip/c_add_DE/c_add_DE_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_add_DE'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
